workdir: "/project/coffea_pangenome/Artocarpus/Assemblies/20241115_JustinAssemblies"
container: "/project/coffea_pangenome/Software/Merondun/apptainers/puzzler.sif"
reference: "/project/coffea_pangenome/Artocarpus/WholeGenomeAlignments/fastas/ASM2540343.fa"
samples:
    HART058:
        hifi: "/project/coffea_pangenome/Artocarpus/Assemblies/20241115_JustinAssemblies/HART058/HART058.HiFi.fastq.gz"
        ploidy: 2
        hic_r1: "/project/coffea_pangenome/Artocarpus/Assemblies/20241115_JustinAssemblies/HART058/HART058.HiC.R1.fastq.gz"
        hic_r2: "/project/coffea_pangenome/Artocarpus/Assemblies/20241115_JustinAssemblies/HART058/HART058.HiC.R2.fastq.gz"
